name: invoice-chain-agent
services:
  - name: backend
    source_dir: /
    github:
      repo: chairulridjaal/invoice-chain-agent
      branch: main
    run_command: cd backend && gunicorn wsgi:application --bind 0.0.0.0:$PORT
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_BASE
        value: "https://openrouter.ai/api/v1"
        scope: RUN_TIME
      - key: CANISTER_ID
        value: "uxrrr-q7777-77774-qaaaq-cai"
        scope: RUN_TIME
      - key: ICP_NETWORK
        value: "testnet"
        scope: RUN_TIME
      - key: PORT
        value: "8080"
        scope: RUN_TIME
      - key: FLASK_ENV
        value: "production"
        scope: RUN_TIME

  - name: frontend
    source_dir: /frontend
    build_command: npm install && npm run build
    run_command: npx serve -s dist -p $PORT
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
